dist: bionic

script:
  - sudo ./travis-build.sh

branches:
  only:
  - main
  - legacy-minimal
  
deploy:
  - provider: script
    script: wget -qO - https://raw.githubusercontent.com/Nitrux/nitrux-repository-util/master/upload-pkgs | sh -s *.deb
    skip_cleanup: true
    on:
      branch: legacy-minimal

notifications:
  email: false
