#! /bin/bash

set -x


#	add add AppImages.

mkdir -p /Applications
mkdir -p /etc/skel/Applications
mkdir -p /etc/skel/.local/bin


{
	printf "%s %s\n" \
		app					"https://github.com/AppImageCrafters/appimage-cli-tool/releases/download/v0.1.4/appimage-cli-tool-0.1.4-x86_64.AppImage" \
		appimaged			"https://github.com/AppImage/appimaged/releases/download/continuous/appimaged-x86_64.AppImage" \
		appimagetool		"https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage" \
		wine				"https://github.com/ferion11/Proton_Appimage/releases/download/continuous/proton-linux-x86-v4.2-PlayOnLinux-x86_64.AppImage"

	printf "%s %s\n" \
		kdenlive			"https://download.kde.org/stable/kdenlive/21.12/linux/kdenlive-21.12.0-x86_64.appimage" \
		libreoffice			"https://libreoffice.soluzioniopen.com/stable/standard/LibreOffice-fresh.standard-x86_64.AppImage" \
		gimp				"https://github.com/mttbernardini/gimp-appimage/releases/download/continuous/GIMP_AppImage-git-2.10.25-20210730-x86_64.AppImage" \
		inkscape			"https://inkscape.org/gallery/item/29256/Inkscape-3bf5ae0-x86_64.AppImage" \
		heroic				"https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/download/v1.10.3/Heroic-1.10.3.AppImage" \
		firefox				"https://github.com/srevinsaju/Firefox-Appimage/releases/download/firefox-v95.0.r20211129150630/firefox-95.0.r20211129150630-x86_64.AppImage"

} | {
	while read name url; do
		axel -a -n 4 -q -k -U "BrightSign/8.2.55.5 (XT1144)Mozilla/5.0 (X11; Linux aarch64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.3 Chrome/69.0.3497.128 Safari/537.36" "$url" -o /Applications/$name
	done
}

chmod +x /Applications/*

mv /Applications/appimaged /etc/skel/.local/bin
