#! /bin/bash

set -xe


#	add add AppImages.

mkdir -p /Applications
mkdir -p /etc/skel/Applications
mkdir -p /etc/skel/.local/bin


{
	printf "%s %s\n" \
		app					"https://github.com/AppImageCrafters/appimage-cli-tool/releases/download/v0.1.4/appimage-cli-tool-0.1.4-x86_64.AppImage" \
		appimaged			"https://github.com/AppImage/appimaged/releases/download/continuous/appimaged-x86_64.AppImage" \
		appimagetool		"https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage" \
		wine				"https://github.com/ferion11/Proton_Appimage/releases/download/continuous/proton-linux-x86-v4.2-PlayOnLinux-x86_64.AppImage"
} | {
	while read name url; do
		axel -a -q -o /Applications/$name "$url"
	done
}

chmod +x /Applications/*

mv /Applications/appimaged /etc/skel/.local/bin
